POST http://localhost:5000/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

iPhone 13
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="01efce7953_50187684_iphone-13.jpg"
Content-Type: image/jpeg

< D:\Images_Videos_Sounds_Design\Images\iphone\01efce7953_50187684_iphone-13.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### delete product
DELETE http://localhost:5000/products/1

###

PATCH http://localhost:5000/products/2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Updated iPhone 13
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="21techfix-phones-superJumbo.jpg"
Content-Type: image/jpeg

< D:\Images_Videos_Sounds_Design\Images\iphone\21techfix-phones-superJumbo.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
